version: '3'
services:
  hfish:
    image: threatbook/hfish-server:latest
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - ./data/hfish:/usr/share/hfish
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 3600